#Contains List of tests
featureRegressionUT = [
#'esalVendorRcToString',
]

fujitsu_testList = [
'esalVendorRcToString',
'esalVendorCreateVlan',
'esalVendorAddPortsToVlan',
#'esalVendorSetPortDefaultVlan',
#'esalVendorSetPortRate',
#'esalVendorGetPortDuplex',
#'esalVendorGetPortAutoNeg',
'esalVendorGetPortLinkState_I',
'esalVendorGetPortLinkState_II',
#'esalVendorGetMacTbl_I',
#'esalVendorGetMacTbl_II',
#'esalVendorPurgeMacEntriesPerPort_I',
#'esalVendorPurgeMacEntriesPerPort_II',
#'esalVendorPurgeMacEntriesPerPort_III',
#'esalVendorGetPortStpState_I',
#'esalVendorGetPortStpState_II',
#'esalVendorGetPortStpState_III',
'esalVendorSetPortStpState_I',
'esalVendorSetPortStpState_II',
'esalVendorSetPortStpState_III',
'esalVendorSetPortStpState_IV',
'esalVendorMirrorPort_I',
'esalVendorMirrorPort_II',
#'esalVendorTagPacketsOnIngress',
#'esalVendorDropUntaggedPacketsOnIngress',
#'esalVendorDisableMacLearningPerPort_I',
#'esalVendorDisableMacLearningPerPort_II',
#'esalVendorDisableMacLearningPerPort_III',
#'esalVendorDisableMacLearningPerPort_IV',
#'esalVendorDisableMacLearningPerPort_V',
#'esalVendorDisableMacLearningPerPort_VI',
#'esalVendorSetFrameMax_I',
#'esalVendorSetFrameMax_II',
]
